### ISSUE TITLE
error reporting & errors running BasicTerm_SE default (simulated) data

### ISSUE THREAD

**Issue by declann** [lifelib-dev/lifelib#70]
Hi,

On BasicTerm_SE using default (simulated) data:

Point ids such as `581`, `956` are failing because they are future NB, age 20 at sale, but that's in almost 3 years.

Even though mortality before sale doesn't affect calculations, there are mortality table lookups which cause failure (`mort_table.xlsx` starts at age 18; lookups for age 17 fail).

I think this is a relatively easy fix to the basic term logic.

Maybe more visibility about errors would be useful, e.g. an error count, which can be included with `result_pv`, which is missing results in cases such as this?

**Comment by fumitoh** [comment]
Thanks for the report. I'll take closer look at it this weekend.

**Comment by fumitoh** [comment]
I added `is_active(t)` and made `pols_death` check it before reading mortality rates. https://github.com/lifelib-dev/lifelib/commit/f5fe26c2577488683481c376900f18e95b1e2575

I'm not entirely sure about the error visibility in `result_pv`. `result_pv` should throw error if something goes wrong in projection for the selected model point, right?

**Comment by declann** [comment]
Thanks for that fix!

You're right about `result_pv` for a selected model point, but this aggregate for the Projection is missing values:

(before the fix)

![image](https://github.com/lifelib-dev/lifelib/assets/353214/c1f21bbb-ca92-464f-8504-b50874641ea4)

Here, it isn't obvious that there are missing values due to errors.

**Comment by declann** [comment]
Oh, correct! So no danger here and closing, thanks!
